---
title: "Introduction"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(samrat)
```

## 1. Reading in our parameters

We start by reading in our parameter file that controls most of our modelling.
Please see [Parameters Vignette](https://ojwatson.github.io/samrat/articles/parameters.html)
for how to set up and format the parameters .xlsx file. 

```{r, parameters}
param_file <- system.file(
  "extdata/som_analysis_parameters.xlsx", package = "samrat"
)

pars_list <- samrat_read_params(param_file)
names(pars_list)
```
We then use this object when reading in our strata and survey metadata:

```{r, surveymeta and strata}
# read in the strata params
strata_file <- system.file(
  "extdata/som_analysis_strata.xlsx", package = "samrat"
)
strata <- samrat_read_strata(strata_file, pars_list)

# read in the survey meta params
surveymeta_file <- system.file(
  "extdata/som_survey_metadata.xlsx", package = "samrat"
)
surveys <- samrat_read_surveymeta(surveymeta_file, pars_list)

```

Similarly when reading in our demography files:

```{r, demog}
# read in the demog params
demog_file <- system.file(
  "extdata/som_demog_data.xlsx", package = "samrat"
)
demog_list <- samrat_read_demography(demog_file, pars_list)
names(demog_list)
```

And lastly when reading in our predictor files:

```{r, predictors}

# read in the predictor params
predictors_file <- system.file(
    "extdata/som_predictor_data.xlsx", package = "samrat"
)

pred_list <- samrat_read_predictors(predictors_file, pars_list)

```
